{{- if .Values.secrets.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llm-training-chart.fullname" . }}
type: Opaque
data:
  apiKey: {{ .Values.secrets.apiKey | b64enc | quote }}
{{- end }}